<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Amul - Gallery</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <!-- Lightbox CSS for image gallery -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.3/css/lightbox.min.css">
    <!-- Animate.css -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">
    <!-- AOS Animation Library -->
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <link rel="stylesheet" href="style.css">
    <!-- InfinityFree compatibility fixes -->
    <link rel="stylesheet" href="infinity-compatibility.css">
    
    <style>
        /* Additional Gallery Styles */
        .gallery-container {
            margin-bottom: 2rem;
        }
        
        .gallery-item {
            margin-bottom: 30px;
            position: relative;
            overflow: hidden;
            border-radius: 10px;
            box-shadow: 0 5px 15px rgba(0,0,0,0.1);
            transition: all 0.3s ease;
        }
        
        .gallery-item:hover {
            transform: translateY(-10px);
            box-shadow: 0 15px 30px rgba(0,0,0,0.2);
        }
        
        .gallery-img {
            width: 100%;
            height: 240px;
            object-fit: cover;
            transition: transform 0.5s ease;
        }
        
        .gallery-item:hover .gallery-img {
            transform: scale(1.05);
        }
        
        /* Explicitly style tabs to work on InfinityFree */
        .gallery-tabs {
            display: flex;
            justify-content: center;
            flex-wrap: wrap;
            margin-bottom: 1rem;
        }
        
        .gallery-tabs .nav-item {
            margin: 5px;
        }
        
        .gallery-tabs .nav-link {
            background-color: #f8f9fa;
            color: #0a4da3;
            border-radius: 30px;
            padding: 8px 16px;
            margin: 0 5px;
            transition: all 0.3s ease;
            display: inline-block;
        }
        
        .gallery-tabs .nav-link.active {
            background-color: #0a4da3;
            color: white;
        }
        
        /* Explicit styles for tab content */
        .tab-content > .tab-pane {
            display: none;
        }
        
        .tab-content > .active {
            display: block;
        }
    </style>
</head>
<body>
<?php include 'header.php'; ?>

<div class="floating-background">
    <!-- Ice cream elements will be generated by JavaScript -->
</div>

<main class="container py-5">
    <div class="row justify-content-center">
        <div class="col-lg-10">
            <div class="content-card animate__animated animate__fadeIn">
                <h1 class="text-center mb-4 animate__animated animate__fadeInDown">Gallery</h1>
                
                <!-- Gallery description -->
                <div class="text-center mb-5" data-aos="fade-up">
                    <p class="lead">Take a visual tour of our store and see what makes Shree Laxmi Amul Shopiee special.</p>
                    <p>Explore our clean, well-maintained store environment and check out our wide range of Amul products.</p>
                </div>
                
                <!-- Gallery tabs with explicit InfinityFree compatibility -->
                <ul class="nav nav-pills gallery-tabs" id="galleryTabs" role="tablist" data-aos="fade-up">
                    <li class="nav-item" role="presentation">
                        <button class="nav-link active" id="store-tab" data-bs-toggle="pill" data-bs-target="#store-photos" type="button" role="tab">
                            <i class="bi bi-shop"></i> Store Photos
                        </button>
                    </li>
                    <li class="nav-item" role="presentation">
                        <button class="nav-link" id="certification-tab" data-bs-toggle="pill" data-bs-target="#certification" type="button" role="tab">
                            <i class="bi bi-patch-check"></i> Certification
                        </button>
                    </li>
                </ul>
                
                <!-- Gallery content -->
                <div class="tab-content" id="galleryTabContent">
                    <!-- Store Photos Tab - No labels as requested -->
                    <div class="tab-pane fade show active" id="store-photos" role="tabpanel" aria-labelledby="store-tab">
                        <div class="gallery-container" data-aos="fade-up">
                            <div class="row g-4">
                                <!-- Row 1 -->
                                <div class="col-6 col-md-4" data-aos="zoom-in" data-aos-delay="100">
                                    <a href="images/shop (1).jpg" data-lightbox="store-gallery" class="gallery-item d-block">
                                        <img src="images/shop (1).jpg" alt="Store Image" class="gallery-img" onerror="this.src='Amul.jpg';">
                                    </a>
                                </div>
                                <div class="col-6 col-md-4" data-aos="zoom-in" data-aos-delay="200">
                                    <a href="images/shop (2).jpg" data-lightbox="store-gallery" class="gallery-item d-block">
                                        <img src="images/shop (2).jpg" alt="Store Image" class="gallery-img" onerror="this.src='Amul.jpg';">
                                    </a>
                                </div>
                                <div class="col-6 col-md-4" data-aos="zoom-in" data-aos-delay="300">
                                    <a href="images/shop (3).jpg" data-lightbox="store-gallery" class="gallery-item d-block">
                                        <img src="images/shop (3).jpg" alt="Store Image" class="gallery-img" onerror="this.src='Amul.jpg';">
                                    </a>
                                </div>
                                
                                <!-- Row 2 -->
                                <div class="col-6 col-md-4" data-aos="zoom-in" data-aos-delay="400">
                                    <a href="images/shop (4).jpg" data-lightbox="store-gallery" class="gallery-item d-block">
                                        <img src="images/shop (4).jpg" alt="Store Image" class="gallery-img" onerror="this.src='Amul.jpg';">
                                    </a>
                                </div>
                                <div class="col-6 col-md-4" data-aos="zoom-in" data-aos-delay="500">
                                    <a href="images/shop (5).jpg" data-lightbox="store-gallery" class="gallery-item d-block">
                                        <img src="images/shop (5).jpg" alt="Store Image" class="gallery-img" onerror="this.src='Amul.jpg';">
                                    </a>
                                </div>
                                <div class="col-6 col-md-4" data-aos="zoom-in" data-aos-delay="600">
                                    <a href="images/shop (6).jpg" data-lightbox="store-gallery" class="gallery-item d-block">
                                        <img src="images/shop (6).jpg" alt="Store Image" class="gallery-img" onerror="this.src='Amul.jpg';">
                                    </a>
                                </div>
                                
                                <!-- Row 3 -->
                                <div class="col-6 col-md-4" data-aos="zoom-in" data-aos-delay="700">
                                    <a href="images/shop (7).jpg" data-lightbox="store-gallery" class="gallery-item d-block">
                                        <img src="images/shop (7).jpg" alt="Store Image" class="gallery-img" onerror="this.src='Amul.jpg';">
                                    </a>
                                </div>
                                <div class="col-6 col-md-4" data-aos="zoom-in" data-aos-delay="800">
                                    <a href="images/shop (8).jpg" data-lightbox="store-gallery" class="gallery-item d-block">
                                        <img src="images/shop (8).jpg" alt="Store Image" class="gallery-img" onerror="this.src='Amul.jpg';">
                                    </a>
                                </div>
                                <div class="col-6 col-md-4" data-aos="zoom-in" data-aos-delay="900">
                                    <a href="images/shop (9).jpg" data-lightbox="store-gallery" class="gallery-item d-block">
                                        <img src="images/shop (9).jpg" alt="Store Image" class="gallery-img" onerror="this.src='Amul.jpg';">
                                    </a>
                                </div>
                                
                                <!-- Row 4 -->
                                <div class="col-6 col-md-4" data-aos="zoom-in" data-aos-delay="1000">
                                    <a href="images/shop (10).jpg" data-lightbox="store-gallery" class="gallery-item d-block">
                                        <img src="images/shop (10).jpg" alt="Store Image" class="gallery-img" onerror="this.src='Amul.jpg';">
                                    </a>
                                </div>
                                <div class="col-6 col-md-4" data-aos="zoom-in" data-aos-delay="1100">
                                    <a href="images/shop (11).jpg" data-lightbox="store-gallery" class="gallery-item d-block">
                                        <img src="images/shop (11).jpg" alt="Store Image" class="gallery-img" onerror="this.src='Amul.jpg';">
                                    </a>
                                </div>
                                <div class="col-6 col-md-4" data-aos="zoom-in" data-aos-delay="1200">
                                    <a href="images/shop (12).jpg" data-lightbox="store-gallery" class="gallery-item d-block">
                                        <img src="images/shop (12).jpg" alt="Store Image" class="gallery-img" onerror="this.src='Amul.jpg';">
                                    </a>
                                </div>
                                
                                <!-- Row 5 -->
                                <div class="col-6 col-md-4" data-aos="zoom-in" data-aos-delay="1300">
                                    <a href="images/shop (13).jpg" data-lightbox="store-gallery" class="gallery-item d-block">
                                        <img src="images/shop (13).jpg" alt="Store Image" class="gallery-img" onerror="this.src='Amul.jpg';">
                                    </a>
                                </div>
                                <div class="col-6 col-md-4" data-aos="zoom-in" data-aos-delay="1400">
                                    <a href="images/shop (14).jpg" data-lightbox="store-gallery" class="gallery-item d-block">
                                        <img src="images/shop (14).jpg" alt="Store Image" class="gallery-img" onerror="this.src='Amul.jpg';">
                                    </a>
                                </div>
                                <div class="col-6 col-md-4" data-aos="zoom-in" data-aos-delay="1500">
                                    <a href="images/shop (15).jpg" data-lightbox="store-gallery" class="gallery-item d-block">
                                        <img src="images/shop (15).jpg" alt="Store Image" class="gallery-img" onerror="this.src='Amul.jpg';">
                                    </a>
                                </div>
                                
                                <!-- Row 6 -->
                                <div class="col-6 col-md-4" data-aos="zoom-in" data-aos-delay="1600">
                                    <a href="images/shop (16).jpg" data-lightbox="store-gallery" class="gallery-item d-block">
                                        <img src="images/shop (16).jpg" alt="Store Image" class="gallery-img" onerror="this.src='Amul.jpg';">
                                    </a>
                                </div>
                                <div class="col-6 col-md-4" data-aos="zoom-in" data-aos-delay="1700">
                                    <a href="images/shop (17).jpg" data-lightbox="store-gallery" class="gallery-item d-block">
                                        <img src="images/shop (17).jpg" alt="Store Image" class="gallery-img" onerror="this.src='Amul.jpg';">
                                    </a>
                                </div>
                                <div class="col-6 col-md-4" data-aos="zoom-in" data-aos-delay="1800">
                                    <a href="images/shop (18).jpg" data-lightbox="store-gallery" class="gallery-item d-block">
                                        <img src="images/shop (18).jpg" alt="Store Image" class="gallery-img" onerror="this.src='Amul.jpg';">
                                    </a>
                                </div>
                                
                                <!-- Row 7 (if needed) -->
                                <div class="col-6 col-md-4 mx-auto" data-aos="zoom-in" data-aos-delay="1900">
                                    <a href="images/shop (19).jpg" data-lightbox="store-gallery" class="gallery-item d-block">
                                        <img src="images/shop (19).jpg" alt="Store Image" class="gallery-img" onerror="this.src='Amul.jpg';">
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <!-- Certification Tab -->
                    <div class="tab-pane fade" id="certification" role="tabpanel" aria-labelledby="certification-tab">
                        <div class="fssai-section" data-aos="fade-up">
                            <div class="row align-items-center">
                                <div class="col-md-6 text-center mb-4 mb-md-0">
                                    <img src="images/FSSAI.jpg" alt="FSSAI Certification" class="img-fluid fssai-img shadow-sm" onerror="this.src='Amul.jpg';">
                                    <a href="images/FSSAI.jpg" data-lightbox="certification" data-title="FSSAI Certification" class="btn btn-sm btn-primary mt-3">
                                        <i class="bi bi-zoom-in"></i> View Full Certificate
                                    </a>
                                </div>
                                <div class="col-md-6">
                                    <h3 class="text-primary mb-4">
                                        <i class="bi bi-patch-check-fill"></i> FSSAI Certified
                                    </h3>
                                    <p class="lead">Our store is proud to be FSSAI approved.</p>
                                    <p>The Food Safety and Standards Authority of India (FSSAI) certification guarantees that our outlet adheres to the highest standards of food safety and hygiene practices.</p>
                                    <div class="d-flex align-items-center mt-4 p-3 bg-light rounded">
                                        <i class="bi bi-shield-check text-success fs-3 me-3"></i>
                                        <div>
                                            <h5 class="mb-1">What this means for you:</h5>
                                            <p class="mb-0">We follow strict quality control processes to ensure that all products are stored and handled properly, maintaining their freshness and nutritional value.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                            <!-- Additional information about FSSAI -->
                            <div class="row mt-5">
                                <div class="col-12">
                                    <div class="card border-0 bg-light">
                                        <div class="card-body">
                                            <h4>About FSSAI Certification</h4>
                                            <p>FSSAI stands for Food Safety and Standards Authority of India. It is an autonomous body established under the Ministry of Health & Family Welfare, Government of India.</p>
                                            <div class="row mt-4">
                                                <div class="col-md-6">
                                                    <h5><i class="bi bi-check-circle-fill text-success me-2"></i> FSSAI Ensures:</h5>
                                                    <ul class="list-group list-group-flush bg-transparent">
                                                        <li class="list-group-item bg-transparent"><i class="bi bi-check text-success me-2"></i> Safe and wholesome food for consumers</li>
                                                        <li class="list-group-item bg-transparent"><i class="bi bi-check text-success me-2"></i> Proper food handling procedures</li>
                                                        <li class="list-group-item bg-transparent"><i class="bi bi-check text-success me-2"></i> Adherence to storage temperature requirements</li>
                                                        <li class="list-group-item bg-transparent"><i class="bi bi-check text-success me-2"></i> Hygienic store environment</li>
                                                    </ul>
                                                </div>
                                                <div class="col-md-6">
                                                    <h5><i class="bi bi-shield-fill-check text-primary me-2"></i> Our Commitment:</h5>
                                                    <ul class="list-group list-group-flush">
                                                        <li class="list-group-item bg-transparent"><i class="bi bi-check text-primary me-2"></i> Regular quality checks of products</li>
                                                        <li class="list-group-item bg-transparent"><i class="bi bi-check text-primary me-2"></i> Trained staff in food safety procedures</li>
                                                        <li class="list-group-item bg-transparent"><i class="bi bi-check text-primary me-2"></i> Maintaining cleanliness throughout the store</li>
                                                        <li class="list-group-item bg-transparent"><i class="bi bi-check text-primary me-2"></i> Proper waste management system</li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

<?php include 'footer.php'; ?>

<!-- Bootstrap JS Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
<!-- Lightbox JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.3/js/lightbox.min.js"></script>
<!-- AOS Animation Library -->
<script src="https://unpkg.com/aos@next/dist/aos.js"></script>
<!-- Ice Cream Background Animation -->
<script src="icecream-bg.js"></script>

<script>
    // Initialize AOS and fix tab functionality for InfinityFree
    document.addEventListener('DOMContentLoaded', function() {
        // Initialize AOS with reduced intensity for better performance
        AOS.init({
            duration: 800,
            easing: 'ease-in-out',
            once: true,
            mirror: false
        });
        
        // Initialize lightbox options
        lightbox.option({
            'resizeDuration': 200,
            'wrapAround': true,
            'fadeDuration': 300,
            'imageFadeDuration': 300,
            'albumLabel': "Image %1 of %2"
        });
        
        // Manual tab functionality for InfinityFree compatibility
        const tabButtons = document.querySelectorAll('#galleryTabs .nav-link');
        const tabPanes = document.querySelectorAll('.tab-pane');
        
        tabButtons.forEach(function(button) {
            button.addEventListener('click', function(e) {
                e.preventDefault();
                
                // Remove active class from all buttons and panes
                tabButtons.forEach(b => b.classList.remove('active'));
                tabPanes.forEach(p => {
                    p.classList.remove('active');
                    p.classList.remove('show');
                });
                
                // Add active class to clicked button
                this.classList.add('active');
                
                // Get target pane
                const targetId = this.getAttribute('data-bs-target');
                const targetPane = document.querySelector(targetId);
                
                if (targetPane) {
                    targetPane.classList.add('active');
                    targetPane.classList.add('show');
                }
            });
        });
    });
</script>
</body>
</html>