<?php
// Check if device is mobile for optimized content delivery
function isMobile() {
    return preg_match("/(android|avantgo|blackberry|bolt|boost|cricket|docomo|fone|hiptop|mini|mobi|palm|phone|pie|tablet|up\.browser|up\.link|webos|wos)/i", 
        $_SERVER['HTTP_USER_AGENT']);
}
$isMobile = isMobile();
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0">
    <title>Amul - Home</title>
    <!-- Mobile-specific meta tags -->
    <meta name="theme-color" content="#0a4da3">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="format-detection" content="telephone=no">
    
    <!-- Performance optimization -->
    <link rel="preconnect" href="https://cdn.jsdelivr.net">
    <link rel="dns-prefetch" href="https://cdn.jsdelivr.net">
    
    <!-- Preloading critical resources -->
    <link rel="preload" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" as="style">
    <link rel="preload" href="<?php echo $isMobile ? 'images/Ice Cream Collection-mobile.jpg' : 'images/Ice Cream Collection.jpg'; ?>" as="image">
    <link rel="preload" href="css/common.css" as="style">
    
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <!-- Animate.css (with reduced payload for mobile) -->
    <?php if ($isMobile): ?>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">
    <?php else: ?>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">
    <?php endif; ?>
    <!-- Core CSS files -->
    <link rel="stylesheet" href="css/common.css">
    <link rel="stylesheet" href="css/layouts/header-footer.css">
    <!-- Page-specific styling -->
    <link rel="stylesheet" href="css/pages/index.css">
    <!-- Mobile optimization CSS -->
    <link rel="stylesheet" href="css/mobile-fixes.css">
    <!-- InfinityFree compatibility fixes -->
    <link rel="stylesheet" href="css/compatibility/infinity-compatibility.css">
    <!-- Animation fixes to ensure colors and animations work -->
    <link rel="stylesheet" href="css/animation-fixes.css">
    <!-- AOS Animation Library (loaded for all devices) -->
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
</head>
<body>

<?php include 'header.php'; ?>

<div class="floating-background">
    <!-- Ice cream elements will be generated by JavaScript -->
</div>

<!-- SECTION 1: HERO - Ultra-Modern Premium Carousel Slider (Fixed) -->
<div class="premium-slider-container mt-3 mb-4">
  <div id="amulCarousel" class="carousel slide premium-carousel" data-bs-ride="carousel">
    <!-- Carousel Progress Bar -->
    <div class="carousel-progress">
      <div class="carousel-progress-bar"></div>
    </div>

    <!-- 3D Carousel Inner -->
    <div class="carousel-inner premium-inner">
      <!-- Slide 1 -->
      <div class="carousel-item active" data-slide-id="1">
        <div class="premium-slide-wrapper">
          <div class="carousel-image-container">
            <img src="images/Ice Cream Collection.jpg" alt="Ice Cream Collection" onerror="this.src='Amul.jpg';">
            <div class="slide-particles" id="particles-1"></div>
            <div class="image-reflections"></div>
          </div>
          <div class="premium-caption">
            <div class="caption-badge">Featured</div>
            <h2 class="slide-title">Delicious<br><span class="highlight">Ice Creams</span></h2>
            <div class="caption-divider"><span></span></div>
            <p class="slide-description">Explore our premium collection of rich, creamy Amul ice creams in various flavors.</p>
            <a href="products.php" class="btn btn-slider">
              <span class="btn-text">Discover Now</span>
              <span class="btn-icon"><i class="bi bi-arrow-right"></i></span>
            </a>
            <div class="slide-number">01</div>
          </div>
        </div>
      </div>

      <!-- Slide 2 -->
      <div class="carousel-item" data-slide-id="2">
        <div class="premium-slide-wrapper">
          <div class="carousel-image-container">
            <img src="images/Dairy Products.jpg" alt="Dairy Products" onerror="this.src='Amul.jpg';">
            <div class="slide-particles" id="particles-2"></div>
            <div class="image-reflections"></div>
          </div>
          <div class="premium-caption">
            <div class="caption-badge">Popular</div>
            <h2 class="slide-title">Fresh<br><span class="highlight">Dairy Products</span></h2>
            <div class="caption-divider"><span></span></div>
            <p class="slide-description">Premium quality butter, cheese and milk products for your daily needs.</p>
            <a href="products.php" class="btn btn-slider">
              <span class="btn-text">Explore Range</span>
              <span class="btn-icon"><i class="bi bi-arrow-right"></i></span>
            </a>
            <div class="slide-number">02</div>
          </div>
        </div>
      </div>

      <!-- Slide 3 -->
      <div class="carousel-item" data-slide-id="3">
        <div class="premium-slide-wrapper">
          <div class="carousel-image-container">
            <img src="images/Refreshing Beverages.jpg" alt="Refreshing Beverages" onerror="this.src='Amul.jpg';">
            <div class="slide-particles" id="particles-3"></div>
            <div class="image-reflections"></div>
          </div>
          <div class="premium-caption">
            <div class="caption-badge">New</div>
            <h2 class="slide-title">Refreshing<br><span class="highlight">Beverages</span></h2>
            <div class="caption-divider"><span></span></div>
            <p class="slide-description">Cool down with Amul's refreshing drink collection for hot summer days.</p>
            <a href="products.php" class="btn btn-slider">
              <span class="btn-text">Try Now</span>
              <span class="btn-icon"><i class="bi bi-arrow-right"></i></span>
            </a>
            <div class="slide-number">03</div>
          </div>
        </div>
      </div>
    </div>
    
    <!-- Premium Controls -->
    <div class="premium-controls">
      <button class="carousel-control-prev premium-control" type="button" data-bs-target="#amulCarousel" data-bs-slide="prev">
        <span class="control-icon">
          <i class="bi bi-chevron-left"></i>
        </span>
      </button>
      <button class="carousel-control-next premium-control" type="button" data-bs-target="#amulCarousel" data-bs-slide="next">
        <span class="control-icon">
          <i class="bi bi-chevron-right"></i>
        </span>
      </button>
    </div>
  </div>
</div>

<!-- SECTION 2: ABOUT US -->
<main class="container py-4">
    <div class="row justify-content-center">
        <div class="col-lg-10">
            <!-- Hero Section -->
            <div class="content-card mb-5" data-aos="fade-up" data-aos-duration="1000">
                <div class="text-center mb-4">
                    <h1 class="animate__animated animate__fadeInDown"><i class="bi bi-cart3"></i> Shree Laxmi Amul Shopiee</h1>
                    <p class="badge bg-danger fs-6 animate__animated animate__fadeIn animate__delay-1s">Official Amul Outlet</p>
                </div>
                
                <div class="row align-items-center">
                    <div class="col-md-6" data-aos="fade-right" data-aos-delay="200">
                        <h2 class="text-primary"><i class="bi bi-cheese"></i> Welcome to Shree Laxmi Amul Shopiee</h2>
                        <p class="lead">Your One-Stop Destination for Fresh & Authentic Amul Products!</p>
                        <p>We are proud to be an official Amul outlet, bringing you the freshest dairy delights, tasty treats, and daily essentials—straight from the house of Amul.</p>
                        <p>Whether you're picking up your favorite butter, sipping on refreshing Amul Kool, or enjoying a scoop of rich Amul ice cream, we've got everything you love—under one roof.</p>
                        <div class="mt-4">
                            <a href="about.php" class="btn btn-primary btn-lg ripple-btn animate__animated animate__pulse animate__infinite">
                                <i class="bi bi-info-circle me-2"></i> Learn More About Us
                            </a>
                        </div>
                    </div>
                    <div class="col-md-6" data-aos="fade-left" data-aos-delay="400">
                        <div class="text-center">
                            <img src="images/iceindex.webp" alt="Amul Products" class="img-fluid rounded shadow-sm floating-img" style="max-height: 300px;">
                        </div>
                    </div>
                </div>
            </div>
            
            <!-- SECTION 3: SERVICES / WHAT WE OFFER -->
            <div class="content-card mb-5 what-we-offer-section" data-aos="fade-up" data-aos-duration="1000">
    <div class="amul-theme-background"></div>
    <h2 class="text-center mb-4 position-relative"><i class="bi bi-cup-hot"></i> What We Offer</h2>
    
    <div class="row row-cols-1 row-cols-md-2 g-4">
        <div class="col" data-aos="zoom-in-up" data-aos-delay="100">
            <div class="card h-100 border-0 shadow-lg service-card service-card-blue">
                <div class="card-body text-center">
                    <div class="icon-box icon-box-blue mb-4">
                        <i class="bi bi-droplet-fill"></i>
                    </div>
                    <h5 class="card-title text-primary">Amul Milk & Dairy Products</h5>
                    <p class="card-text">Fresh milk, curd, and other dairy essentials for your daily needs.</p>
                </div>
                <div class="card-animation-element"></div>
            </div>
        </div>
        <div class="col" data-aos="zoom-in-up" data-aos-delay="200">
            <div class="card h-100 border-0 shadow-lg service-card service-card-red">
                <div class="card-body text-center">
                    <div class="icon-box icon-box-red mb-4">
                        <i class="bi bi-snow2"></i>
                    </div>
                    <h5 class="card-title text-danger">Ice Creams & Desserts</h5>
                    <p class="card-text">Delicious ice creams and frozen desserts in various flavors.</p>
                </div>
                <div class="card-animation-element"></div>
            </div>
        </div>
        <div class="col" data-aos="zoom-in-up" data-aos-delay="300">
            <div class="card h-100 border-0 shadow-lg service-card service-card-orange">
                <div class="card-body text-center">
                    <div class="icon-box icon-box-orange mb-4">
                        <i class="bi bi-cup-straw"></i>
                    </div>
                    <h5 class="card-title text-warning">Chocolates & Beverages</h5>
                    <p class="card-text">Tasty chocolates and refreshing beverages for all ages.</p>
                </div>
                <div class="card-animation-element"></div>
            </div>
        </div>
        <div class="col" data-aos="zoom-in-up" data-aos-delay="400">
            <div class="card h-100 border-0 shadow-lg service-card service-card-green">
                <div class="card-body text-center">
                    <div class="icon-box icon-box-green mb-4">
                        <i class="bi bi-egg-fried"></i>
                    </div>
                    <h5 class="card-title text-success">Paneer, Cheese, Butter & More</h5>
                    <p class="card-text">Wide range of dairy products for your cooking needs.</p>
                </div>
                <div class="card-animation-element"></div>
            </div>
        </div>
    </div>
    
    <div class="text-center mt-4" data-aos="zoom-in" data-aos-delay="500">
        <div class="alert alert-info alert-amul" role="alert">
            <div class="alert-icon"><i class="bi bi-info-circle-fill"></i></div>
            <div class="alert-text">Wholesale & Retail Options Available</div>
        </div>
    </div>
</div>
            
            <!-- SECTION 4: WHY CHOOSE US -->
            <div class="content-card mb-5 benefits-section" data-aos="fade-up" data-aos-duration="1000">
                <h2 class="text-center mb-5"><i class="bi bi-bell"></i> Why Choose Us?</h2>
                
                <div class="row">
                    <div class="col-md-6 mb-4" data-aos="fade-right" data-aos-delay="100">
                        <div class="benefit-card d-flex align-items-center">
                            <div class="flex-shrink-0">
                                <div class="benefit-icon">
                                    <i class="bi bi-patch-check"></i>
                                </div>
                            </div>
                            <div class="flex-grow-1 ms-3">
                                <h5>100% Genuine Amul Products</h5>
                                <p class="mb-0">Authorized Amul outlet with authentic products</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 mb-4" data-aos="fade-left" data-aos-delay="200">
                        <div class="benefit-card d-flex align-items-center">
                            <div class="flex-shrink-0">
                                <div class="benefit-icon">
                                    <i class="bi bi-tag"></i>
                                </div>
                            </div>
                            <div class="flex-grow-1 ms-3">
                                <h5>Best Prices Guaranteed</h5>
                                <p class="mb-0">Competitive pricing for all our products</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 mb-4" data-aos="fade-right" data-aos-delay="300">
                        <div class="benefit-card d-flex align-items-center">
                            <div class="flex-shrink-0">
                                <div class="benefit-icon">
                                    <i class="bi bi-people"></i>
                                </div>
                            </div>
                            <div class="flex-grow-1 ms-3">
                                <h5>Friendly & Quick Service</h5>
                                <p class="mb-0">Courteous staff ready to assist you</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 mb-4" data-aos="fade-left" data-aos-delay="400">
                        <div class="benefit-card d-flex align-items-center">
                            <div class="flex-shrink-0">
                                <div class="benefit-icon">
                                    <i class="bi bi-stars"></i>
                                </div>
                            </div>
                            <div class="flex-grow-1 ms-3">
                                <h5>Clean, Hygienic Store Environment</h5>
                                <p class="mb-0">Maintaining highest standards of cleanliness</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            <!-- SECTION 5: PRODUCTS HIGHLIGHTS -->
            <div class="content-card mb-5 products-highlight" data-aos="fade-up" data-aos-duration="1200">
                <h2 class="text-center mb-4"><i class="bi bi-basket"></i> Featured Products</h2>
                <p class="text-center mb-5">Discover our most popular Amul products loved by customers</p>
                
                <div class="row row-cols-2 row-cols-md-4 g-4">
                    <div class="col" data-aos="flip-left" data-aos-delay="100">
                        <div class="product-thumbnail">
                            <div class="product-img-wrapper">
                                <img src="images/Tricone.jpg" alt="Amul Tricone" class="img-fluid rounded product-img">
                                <div class="product-overlay">
                                    <a href="products.php" class="btn btn-sm btn-light">View Details</a>
                                </div>
                            </div>
                            <div class="product-badge"><span>Popular</span></div>
                            <h5 class="mt-2 text-center">Amul Tricone</h5>
                        </div>
                    </div>
                    <div class="col" data-aos="flip-left" data-aos-delay="200">
                        <div class="product-thumbnail">
                            <div class="product-img-wrapper">
                                <img src="images/Amul Butter.jpg" alt="Amul Butter" class="img-fluid rounded product-img">
                                <div class="product-overlay">
                                    <a href="products.php" class="btn btn-sm btn-light">View Details</a>
                                </div>
                            </div>
                            <div class="product-badge"><span>Classic</span></div>
                            <h5 class="mt-2 text-center">Amul Butter</h5>
                        </div>
                    </div>
                    <div class="col" data-aos="flip-left" data-aos-delay="300">
                        <div class="product-thumbnail">
                            <div class="product-img-wrapper">
                                <img src="images/Amul Taaza Milk.jpg" alt="Amul Taaza Milk" class="img-fluid rounded product-img">
                                <div class="product-overlay">
                                    <a href="products.php" class="btn btn-sm btn-light">View Details</a>
                                </div>
                            </div>
                            <div class="product-badge"><span>Essential</span></div>
                            <h5 class="mt-2 text-center">Amul Taaza Milk</h5>
                        </div>
                    </div>
                    <div class="col" data-aos="flip-left" data-aos-delay="400">
                        <div class="product-thumbnail">
                            <div class="product-img-wrapper">
                                <img src="images/Mango Lassi.jpg" alt="Mango Lassi" class="img-fluid rounded product-img">
                                <div class="product-overlay">
                                    <a href="products.php" class="btn btn-sm btn-light">View Details</a>
                                </div>
                            </div>
                            <div class="product-badge"><span>Refreshing</span></div>
                            <h5 class="mt-2 text-center">Mango Lassi</h5>
                        </div>
                    </div>
                </div>
                
                <div class="text-center mt-4" data-aos="zoom-in" data-aos-delay="500">
                    <a href="products.php" class="btn btn-outline-primary btn-lg animated-button">
                        <span class="button-text"><i class="bi bi-grid me-2"></i> View All Products</span>
                        <span class="button-animation"></span>
                    </a>
                </div>
            </div>
            
            <!-- SECTION 6: TESTIMONIALS -->
            <div class="content-card mb-5 testimonials-section" data-aos="fade-up" data-aos-duration="1200">
                <h2 class="text-center mb-5"><i class="bi bi-chat-quote"></i> What Our Customers Say</h2>
                
                <div id="testimonialCarousel" class="carousel slide" data-bs-ride="carousel">
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <div class="testimonial-card">
                                <div class="testimonial-rating">
                                    <i class="bi bi-star-fill"></i>
                                    <i class="bi bi-star-fill"></i>
                                    <i class="bi bi-star-fill"></i>
                                    <i class="bi bi-star-fill"></i>
                                    <i class="bi bi-star-fill"></i>
                                </div>
                                <p class="testimonial-text">"I've been shopping at Shree Laxmi Amul Shopiee for years. The quality of their products is consistently excellent, and the staff is always helpful and friendly. The best place to get Amul products in Pachmarg!"</p>
                                <div class="testimonial-author">
                                    <div class="testimonial-avatar">
                                        <i class="bi bi-person-circle"></i>
                                    </div>
                                    <h5>Suresh Patel</h5>
                                </div>
                            </div>
                        </div>
                        <div class="carousel-item">
                            <div class="testimonial-card">
                                <div class="testimonial-rating">
                                    <i class="bi bi-star-fill"></i>
                                    <i class="bi bi-star-fill"></i>
                                    <i class="bi bi-star-fill"></i>
                                    <i class="bi bi-star-fill"></i>
                                    <i class="bi bi-star-half"></i>
                                </div>
                                <p class="testimonial-text">"Their ice cream selection is amazing! My kids love visiting the shop after school. The prices are fair and the store is always clean and well-maintained. Highly recommended!"</p>
                                <div class="testimonial-author">
                                    <div class="testimonial-avatar">
                                        <i class="bi bi-person-circle"></i>
                                    </div>
                                    <h5>Priya Sharma</h5>
                                </div>
                            </div>
                        </div>
                        <div class="carousel-item">
                            <div class="testimonial-card">
                                <div class="testimonial-rating">
                                    <i class="bi bi-star-fill"></i>
                                    <i class="bi bi-star-fill"></i>
                                    <i class="bi bi-star-fill"></i>
                                    <i class="bi bi-star-fill"></i>
                                    <i class="bi bi-star-fill"></i>
                                </div>
                                <p class="testimonial-text">"As a restaurant owner, I depend on Shree Laxmi Amul Shopiee for bulk supplies of cheese and butter. Their wholesale prices are competitive and delivery is always on time. Great business partner!"</p>
                                <div class="testimonial-author">
                                    <div class="testimonial-avatar">
                                        <i class="bi bi-person-circle"></i>
                                    </div>
                                    <h5>Raj Malhotra</h5>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="testimonial-controls">
                        <button class="carousel-control-prev testimonial-control" type="button" data-bs-target="#testimonialCarousel" data-bs-slide="prev">
                            <i class="bi bi-chevron-left"></i>
                        </button>
                        <button class="carousel-control-next testimonial-control" type="button" data-bs-target="#testimonialCarousel" data-bs-slide="next">
                            <i class="bi bi-chevron-right"></i>
                        </button>
                    </div>
                </div>
            </div>
            
            <!-- SECTION 7: VISIT US -->
            <div class="content-card mb-5 location-section" data-aos="fade-up" data-aos-duration="1000">
                <h2 class="text-center mb-4"><i class="bi bi-geo-alt"></i> Visit Us Today!</h2>
                
                <div class="row justify-content-center">
                    <div class="col-md-6" data-aos="fade-right" data-aos-delay="200">
                        <div class="map-container">
                            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3760.227876302633!2d72.85!3d19.55!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMTnCsDMwJzAwLjAiTiA3MsKwNTAnMjQuMCJF!5e0!3m2!1sen!2sin!4v1620112345678!5m2!1sen!2sin" width="100%" height="300" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
                        </div>
                    </div>
                    <div class="col-md-6" data-aos="fade-left" data-aos-delay="300">
                        <div class="card border-0 bg-light h-100">
                            <div class="card-body">
                                <ul class="list-group list-group-flush">
                                    <li class="list-group-item bg-transparent location-item">
                                        <i class="bi bi-geo-alt-fill text-danger"></i> <strong>Location:</strong> Shree Laxmi Amul Shopiee, [Pachmarg]
                                    </li>
                                    <li class="list-group-item bg-transparent location-item">
                                        <i class="bi bi-clock-fill text-danger"></i> <strong>Timing:</strong> Open Daily – 7:00 AM to 11:00 PM
                                    </li>
                                    <li class="list-group-item bg-transparent location-item">
                                        <i class="bi bi-telephone-fill text-danger"></i> <strong>Contact:</strong> +91 9890377098
                                    </li>
                                </ul>
                                <div class="text-center mt-3">
                                    <a href="https://maps.app.goo.gl/pG3D8cZ4Udd39mgs9" target="_blank" class="btn btn-danger pulsate-btn">
                                        <i class="bi bi-map me-2"></i> Get Directions
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            <!-- SECTION 8: CALL TO ACTION -->
            <div class="content-card mb-5 cta-section" data-aos="fade-up" data-aos-duration="1000">
                <div class="text-center py-4">
                    <h2 class="text-danger mb-4" data-aos="zoom-in" data-aos-delay="100"><i class="bi bi-heart"></i> Thank You for Trusting Shree Laxmi Amul Shopiee!</h2>
                    <p class="fst-italic mb-4" data-aos="fade-up" data-aos-delay="200">"Amul – The Taste of India, Now at Your Neighborhood Store."</p>
                    <div class="mt-4 d-flex justify-content-center flex-wrap gap-3">
                        <a href="contact.php" class="btn btn-lg cta-button" data-aos="flip-up" data-aos-delay="300">
                            <span><i class="bi bi-headset me-2"></i> Contact Us Today</span>
                        </a>
                    </div>
                </div>
            </div>

            
        </div>
    </div>
</main>

<?php include 'footer.php'; ?>

<!-- Bootstrap JS Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
<!-- InfinityFree compatibility fixes -->
<script src="infinity-fixes.js"></script>

<!-- AOS Animation Library (always loaded) -->
<script src="https://unpkg.com/aos@next/dist/aos.js"></script>

<!-- Animation fixes script -->
<script src="animations.js"></script>

<!-- Additional page-specific animations -->
<script>
document.addEventListener('DOMContentLoaded', function() {
    // Initialize all animations via our animation script
    
    // Extra animations for this page
    document.querySelectorAll('.product-thumbnail').forEach(product => {
        product.addEventListener('mouseenter', function() {
            this.classList.add('animate__animated', 'animate__pulse');
        });
        
        product.addEventListener('mouseleave', function() {
            this.classList.remove('animate__animated', 'animate__pulse');
        });
    });
    
    // Enable all animations that might be disabled
    document.querySelectorAll('.animate__animated').forEach(el => {
        // Make sure animations aren't disabled
        el.style.animationDuration = '';
        el.style.animationDelay = '';
    });
    
    // Initialize AOS with more dynamic settings
    if (typeof AOS !== 'undefined') {
        AOS.init({
            duration: 800,
            easing: 'ease-in-out',
            once: false,
            mirror: false
        });
        
        // Refresh AOS when scrolling to catch any missed animations
        window.addEventListener('scroll', function() {
            AOS.refresh();
        }, {passive: true});
    }
});
</script>

<!-- IntersectionObserver for lazy loading and animation -->
<script>
document.addEventListener('DOMContentLoaded', function() {
    // Use IntersectionObserver for lazy loading and animations
    if ('IntersectionObserver' in window) {
        // Lazy load images
        const lazyImages = document.querySelectorAll('img[loading="lazy"]');
        const imageObserver = new IntersectionObserver((entries) => {
            entries.forEach(entry => {
                if (entry.isIntersecting) {
                    const image = entry.target;
                    if (image.dataset.src) {
                        image.src = image.dataset.src;
                        image.removeAttribute('data-src');
                    }
                    image.classList.add('loaded');
                    imageObserver.unobserve(image);
                }
            });
        });
        
        lazyImages.forEach(img => imageObserver.observe(img));
        
        // Animate elements when they scroll into view
        <?php if (!$isMobile): ?>
        const animatedElems = document.querySelectorAll('.animate-on-scroll');
        const animationObserver = new IntersectionObserver((entries) => {
            entries.forEach(entry => {
                if (entry.isIntersecting) {
                    entry.target.classList.add('visible');
                    animationObserver.unobserve(entry.target);
                }
            });
        });
        
        animatedElems.forEach(elem => animationObserver.observe(elem));
        <?php else: ?>
        // Just show elements immediately on mobile for better performance
        document.querySelectorAll('.animate-on-scroll').forEach(el => {
            el.classList.add('visible');
        });
        <?php endif; ?>
    }
});
</script>
</body>
</html>