<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nutritional Information - Shree Laxmi Amul Shopiee</title>    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <!-- Animate.css -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">
    <!-- Site-specific styling -->
    <link rel="stylesheet" href="style.css">
    <!-- Mobile optimization CSS -->
    <link rel="stylesheet" href="mobile-fixes.css">
    <!-- InfinityFree compatibility fixes -->
    <link rel="stylesheet" href="infinity-compatibility.css">
</head>
<body>

<?php include 'header.php'; ?>

<div class="floating-background">
    <!-- Ice cream elements will be generated by JavaScript -->
</div>

<main class="container py-5">
    <div class="row justify-content-center">
        <div class="col-lg-10">
            <div class="content-card animate__animated animate__fadeIn">
                <h1 class="text-center mb-4 animate__animated animate__fadeInDown">Nutritional Information</h1>
                <p class="lead text-center mb-5">Learn about the nutritional values of various Amul products to make informed choices for your diet.</p>
                
                <!-- Nutritional Info Categories Tabs -->
                <ul class="nav nav-pills mb-4 justify-content-center" id="nutritionTabs" role="tablist">
                    <li class="nav-item" role="presentation">
                        <button class="nav-link active" id="dairy-tab" data-bs-toggle="pill" data-bs-target="#dairy" type="button" role="tab">
                            <i class="bi bi-droplet"></i> Dairy Products
                        </button>
                    </li>
                    <li class="nav-item" role="presentation">
                        <button class="nav-link" id="ice-cream-tab" data-bs-toggle="pill" data-bs-target="#ice-cream" type="button" role="tab">
                            <i class="bi bi-snow2"></i> Ice Creams
                        </button>
                    </li>
                    <li class="nav-item" role="presentation">
                        <button class="nav-link" id="beverages-tab" data-bs-toggle="pill" data-bs-target="#beverages" type="button" role="tab">
                            <i class="bi bi-cup-straw"></i> Beverages
                        </button>
                    </li>
                </ul>
                
                <!-- Nutritional Info Content -->
                <div class="tab-content" id="nutritionTabContent">
                    <!-- Dairy Products Tab -->
                    <div class="tab-pane fade show active" id="dairy" role="tabpanel">
                        <div class="card mb-4">
                            <div class="card-header bg-primary text-white">
                                <h4 class="mb-0">Amul Butter (100g)</h4>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-striped table-hover">
                                        <thead>
                                            <tr>
                                                <th>Nutrient</th>
                                                <th>Amount per 100g</th>
                                                <th>% Daily Value*</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>Calories</td>
                                                <td>722 kcal</td>
                                                <td>36%</td>
                                            </tr>
                                            <tr>
                                                <td>Total Fat</td>
                                                <td>80g</td>
                                                <td>123%</td>
                                            </tr>
                                            <tr>
                                                <td>- Saturated Fat</td>
                                                <td>50g</td>
                                                <td>250%</td>
                                            </tr>
                                            <tr>
                                                <td>Cholesterol</td>
                                                <td>215mg</td>
                                                <td>72%</td>
                                            </tr>
                                            <tr>
                                                <td>Sodium</td>
                                                <td>650mg</td>
                                                <td>28%</td>
                                            </tr>
                                            <tr>
                                                <td>Total Carbohydrate</td>
                                                <td>0.1g</td>
                                                <td>0%</td>
                                            </tr>
                                            <tr>
                                                <td>Protein</td>
                                                <td>0.5g</td>
                                                <td>1%</td>
                                            </tr>
                                            <tr>
                                                <td>Vitamin A</td>
                                                <td>3500 IU</td>
                                                <td>70%</td>
                                            </tr>
                                            <tr>
                                                <td>Vitamin D</td>
                                                <td>25 IU</td>
                                                <td>6%</td>
                                            </tr>
                                            <tr>
                                                <td>Calcium</td>
                                                <td>24mg</td>
                                                <td>2%</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        
                        <div class="card mb-4">
                            <div class="card-header bg-warning text-dark">
                                <h4 class="mb-0">Amul Cheese (100g)</h4>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-striped table-hover">
                                        <thead>
                                            <tr>
                                                <th>Nutrient</th>
                                                <th>Amount per 100g</th>
                                                <th>% Daily Value*</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>Calories</td>
                                                <td>348 kcal</td>
                                                <td>17%</td>
                                            </tr>
                                            <tr>
                                                <td>Total Fat</td>
                                                <td>25g</td>
                                                <td>38%</td>
                                            </tr>
                                            <tr>
                                                <td>- Saturated Fat</td>
                                                <td>16g</td>
                                                <td>80%</td>
                                            </tr>
                                            <tr>
                                                <td>Cholesterol</td>
                                                <td>70mg</td>
                                                <td>23%</td>
                                            </tr>
                                            <tr>
                                                <td>Sodium</td>
                                                <td>780mg</td>
                                                <td>34%</td>
                                            </tr>
                                            <tr>
                                                <td>Total Carbohydrate</td>
                                                <td>4.5g</td>
                                                <td>1.5%</td>
                                            </tr>
                                            <tr>
                                                <td>Protein</td>
                                                <td>22g</td>
                                                <td>44%</td>
                                            </tr>
                                            <tr>
                                                <td>Calcium</td>
                                                <td>700mg</td>
                                                <td>70%</td>
                                            </tr>
                                            <tr>
                                                <td>Vitamin A</td>
                                                <td>300 IU</td>
                                                <td>6%</td>
                                            </tr>
                                            <tr>
                                                <td>Vitamin B12</td>
                                                <td>1.5μg</td>
                                                <td>62%</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        
                        <div class="card mb-4">
                            <div class="card-header bg-info text-dark">
                                <h4 class="mb-0">Amul Paneer (100g)</h4>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-striped table-hover">
                                        <thead>
                                            <tr>
                                                <th>Nutrient</th>
                                                <th>Amount per 100g</th>
                                                <th>% Daily Value*</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>Calories</td>
                                                <td>265 kcal</td>
                                                <td>13%</td>
                                            </tr>
                                            <tr>
                                                <td>Total Fat</td>
                                                <td>20g</td>
                                                <td>31%</td>
                                            </tr>
                                            <tr>
                                                <td>- Saturated Fat</td>
                                                <td>13g</td>
                                                <td>65%</td>
                                            </tr>
                                            <tr>
                                                <td>Cholesterol</td>
                                                <td>70mg</td>
                                                <td>23%</td>
                                            </tr>
                                            <tr>
                                                <td>Sodium</td>
                                                <td>30mg</td>
                                                <td>1%</td>
                                            </tr>
                                            <tr>
                                                <td>Total Carbohydrate</td>
                                                <td>3g</td>
                                                <td>1%</td>
                                            </tr>
                                            <tr>
                                                <td>Protein</td>
                                                <td>18g</td>
                                                <td>36%</td>
                                            </tr>
                                            <tr>
                                                <td>Calcium</td>
                                                <td>500mg</td>
                                                <td>50%</td>
                                            </tr>
                                            <tr>
                                                <td>Vitamin A</td>
                                                <td>210 IU</td>
                                                <td>4%</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        
                        <div class="alert alert-info">
                            <i class="bi bi-info-circle-fill me-2"></i> The nutritional values provided are approximate and may vary slightly. Please refer to product packaging for the most accurate information.
                        </div>
                    </div>
                    
                    <!-- Ice Cream Tab -->
                    <div class="tab-pane fade" id="ice-cream" role="tabpanel">
                        <div class="card mb-4">
                            <div class="card-header bg-primary text-white">
                                <h4 class="mb-0">Amul Vanilla Ice Cream (100g)</h4>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-striped table-hover">
                                        <thead>
                                            <tr>
                                                <th>Nutrient</th>
                                                <th>Amount per 100g</th>
                                                <th>% Daily Value*</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>Calories</td>
                                                <td>207 kcal</td>
                                                <td>10%</td>
                                            </tr>
                                            <tr>
                                                <td>Total Fat</td>
                                                <td>10g</td>
                                                <td>15%</td>
                                            </tr>
                                            <tr>
                                                <td>- Saturated Fat</td>
                                                <td>6g</td>
                                                <td>30%</td>
                                            </tr>
                                            <tr>
                                                <td>Cholesterol</td>
                                                <td>30mg</td>
                                                <td>10%</td>
                                            </tr>
                                            <tr>
                                                <td>Sodium</td>
                                                <td>50mg</td>
                                                <td>2%</td>
                                            </tr>
                                            <tr>
                                                <td>Total Carbohydrate</td>
                                                <td>25g</td>
                                                <td>8%</td>
                                            </tr>
                                            <tr>
                                                <td>- Sugars</td>
                                                <td>22g</td>
                                                <td>-</td>
                                            </tr>
                                            <tr>
                                                <td>Protein</td>
                                                <td>3.5g</td>
                                                <td>7%</td>
                                            </tr>
                                            <tr>
                                                <td>Calcium</td>
                                                <td>120mg</td>
                                                <td>12%</td>
                                            </tr>
                                            <tr>
                                                <td>Vitamin A</td>
                                                <td>300 IU</td>
                                                <td>6%</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        
                        <div class="card mb-4">
                            <div class="card-header bg-warning text-dark">
                                <h4 class="mb-0">Amul Chocolate Ice Cream (100g)</h4>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-striped table-hover">
                                        <thead>
                                            <tr>
                                                <th>Nutrient</th>
                                                <th>Amount per 100g</th>
                                                <th>% Daily Value*</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>Calories</td>
                                                <td>216 kcal</td>
                                                <td>11%</td>
                                            </tr>
                                            <tr>
                                                <td>Total Fat</td>
                                                <td>11g</td>
                                                <td>17%</td>
                                            </tr>
                                            <tr>
                                                <td>- Saturated Fat</td>
                                                <td>7g</td>
                                                <td>35%</td>
                                            </tr>
                                            <tr>
                                                <td>Cholesterol</td>
                                                <td>30mg</td>
                                                <td>10%</td>
                                            </tr>
                                            <tr>
                                                <td>Sodium</td>
                                                <td>55mg</td>
                                                <td>2%</td>
                                            </tr>
                                            <tr>
                                                <td>Total Carbohydrate</td>
                                                <td>26g</td>
                                                <td>9%</td>
                                            </tr>
                                            <tr>
                                                <td>- Sugars</td>
                                                <td>24g</td>
                                                <td>-</td>
                                            </tr>
                                            <tr>
                                                <td>Protein</td>
                                                <td>3.7g</td>
                                                <td>7%</td>
                                            </tr>
                                            <tr>
                                                <td>Calcium</td>
                                                <td>125mg</td>
                                                <td>12%</td>
                                            </tr>
                                            <tr>
                                                <td>Iron</td>
                                                <td>0.5mg</td>
                                                <td>3%</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        
                        <div class="card mb-4">
                            <div class="card-header bg-success text-white">
                                <h4 class="mb-0">Amul Tricone Ice Cream (70g cone)</h4>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-striped table-hover">
                                        <thead>
                                            <tr>
                                                <th>Nutrient</th>
                                                <th>Amount per cone</th>
                                                <th>% Daily Value*</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>Calories</td>
                                                <td>165 kcal</td>
                                                <td>8%</td>
                                            </tr>
                                            <tr>
                                                <td>Total Fat</td>
                                                <td>7g</td>
                                                <td>11%</td>
                                            </tr>
                                            <tr>
                                                <td>- Saturated Fat</td>
                                                <td>4.5g</td>
                                                <td>22%</td>
                                            </tr>
                                            <tr>
                                                <td>Cholesterol</td>
                                                <td>20mg</td>
                                                <td>7%</td>
                                            </tr>
                                            <tr>
                                                <td>Sodium</td>
                                                <td>40mg</td>
                                                <td>2%</td>
                                            </tr>
                                            <tr>
                                                <td>Total Carbohydrate</td>
                                                <td>22g</td>
                                                <td>7%</td>
                                            </tr>
                                            <tr>
                                                <td>- Sugars</td>
                                                <td>18g</td>
                                                <td>-</td>
                                            </tr>
                                            <tr>
                                                <td>Protein</td>
                                                <td>2.5g</td>
                                                <td>5%</td>
                                            </tr>
                                            <tr>
                                                <td>Calcium</td>
                                                <td>80mg</td>
                                                <td>8%</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        
                        <div class="alert alert-info">
                            <i class="bi bi-info-circle-fill me-2"></i> The nutritional values provided are approximate and may vary slightly. Please refer to product packaging for the most accurate information.
                        </div>
                    </div>
                    
                    <!-- Beverages Tab -->
                    <div class="tab-pane fade" id="beverages" role="tabpanel">
                        <div class="card mb-4">
                            <div class="card-header bg-primary text-white">
                                <h4 class="mb-0">Amul Kool Flavored Milk (200ml)</h4>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-striped table-hover">
                                        <thead>
                                            <tr>
                                                <th>Nutrient</th>
                                                <th>Amount per 200ml</th>
                                                <th>% Daily Value*</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>Calories</td>
                                                <td>170 kcal</td>
                                                <td>8.5%</td>
                                            </tr>
                                            <tr>
                                                <td>Total Fat</td>
                                                <td>6g</td>
                                                <td>9%</td>
                                            </tr>
                                            <tr>
                                                <td>- Saturated Fat</td>
                                                <td>3.5g</td>
                                                <td>17.5%</td>
                                            </tr>
                                            <tr>
                                                <td>Cholesterol</td>
                                                <td>20mg</td>
                                                <td>7%</td>
                                            </tr>
                                            <tr>
                                                <td>Sodium</td>
                                                <td>70mg</td>
                                                <td>3%</td>
                                            </tr>
                                            <tr>
                                                <td>Total Carbohydrate</td>
                                                <td>24g</td>
                                                <td>8%</td>
                                            </tr>
                                            <tr>
                                                <td>- Sugars</td>
                                                <td>22g</td>
                                                <td>-</td>
                                            </tr>
                                            <tr>
                                                <td>Protein</td>
                                                <td>5g</td>
                                                <td>10%</td>
                                            </tr>
                                            <tr>
                                                <td>Calcium</td>
                                                <td>230mg</td>
                                                <td>23%</td>
                                            </tr>
                                            <tr>
                                                <td>Vitamin D</td>
                                                <td>1.5μg</td>
                                                <td>7.5%</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        
                        <div class="card mb-4">
                            <div class="card-header bg-success text-white">
                                <h4 class="mb-0">Amul Buttermilk (200ml)</h4>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-striped table-hover">
                                        <thead>
                                            <tr>
                                                <th>Nutrient</th>
                                                <th>Amount per 200ml</th>
                                                <th>% Daily Value*</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>Calories</td>
                                                <td>80 kcal</td>
                                                <td>4%</td>
                                            </tr>
                                            <tr>
                                                <td>Total Fat</td>
                                                <td>1.5g</td>
                                                <td>2%</td>
                                            </tr>
                                            <tr>
                                                <td>- Saturated Fat</td>
                                                <td>1g</td>
                                                <td>5%</td>
                                            </tr>
                                            <tr>
                                                <td>Cholesterol</td>
                                                <td>5mg</td>
                                                <td>2%</td>
                                            </tr>
                                            <tr>
                                                <td>Sodium</td>
                                                <td>120mg</td>
                                                <td>5%</td>
                                            </tr>
                                            <tr>
                                                <td>Total Carbohydrate</td>
                                                <td>12g</td>
                                                <td>4%</td>
                                            </tr>
                                            <tr>
                                                <td>- Sugars</td>
                                                <td>11g</td>
                                                <td>-</td>
                                            </tr>
                                            <tr>
                                                <td>Protein</td>
                                                <td>3g</td>
                                                <td>6%</td>
                                            </tr>
                                            <tr>
                                                <td>Calcium</td>
                                                <td>140mg</td>
                                                <td>14%</td>
                                            </tr>
                                            <tr>
                                                <td>Probiotics</td>
                                                <td>Present</td>
                                                <td>-</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        
                        <div class="alert alert-info">
                            <i class="bi bi-info-circle-fill me-2"></i> The nutritional values provided are approximate and may vary slightly. Please refer to product packaging for the most accurate information.
                        </div>
                    </div>
                </div>
                
                <!-- Nutritional Info Disclaimer -->
                <div class="card bg-light mt-5">
                    <div class="card-body">
                        <h4 class="text-center mb-4"><i class="bi bi-shield-check"></i> Understanding Nutritional Information</h4>
                        <div class="row">
                            <div class="col-md-6">
                                <h5><i class="bi bi-info-circle text-primary me-2"></i> Daily Values</h5>
                                <p>* Percent Daily Values are based on a 2,000 calorie diet. Your daily values may be higher or lower depending on your calorie needs.</p>
                                <p>The nutritional information provided is based on standard serving sizes and may vary slightly from batch to batch.</p>
                            </div>
                            <div class="col-md-6">
                                <h5><i class="bi bi-exclamation-triangle text-warning me-2"></i> Important Note</h5>
                                <p>If you have specific dietary needs or allergies, please consult with a healthcare professional before consuming these products.</p>
                                <p>For the most up-to-date and accurate information, always refer to the nutritional information printed on the product packaging.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

<?php include 'footer.php'; ?>

<!-- Bootstrap JS Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
<!-- Ice Cream Background Animation -->
<script src="js/icecream-bg.js"></script>
<!-- InfinityFree compatibility fixes -->
<script src="infinity-fixes.js"></script>
</body>
</html>
