<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Privacy Policy - Shree Laxmi Amul Shopiee</title>    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <!-- Animate.css for animations -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">
    <!-- Site-specific styling -->
    <link rel="stylesheet" href="style.css">
    <!-- Mobile optimization CSS -->
    <link rel="stylesheet" href="mobile-fixes.css">
    <!-- InfinityFree compatibility fixes -->
    <link rel="stylesheet" href="infinity-compatibility.css">
</head>
<body>

<?php include 'header.php'; ?>

<div class="floating-background">
    <!-- Ice cream elements will be generated by JavaScript -->
</div>

<main class="container py-5">
    <div class="row justify-content-center">
        <div class="col-lg-10">
            <div class="content-card">
                <h1 class="text-center mb-4">Privacy Policy</h1>
                <p class="lead text-center mb-5">Your privacy is important to us. This Privacy Policy explains how we collect, use, and protect your personal information.</p>
                
                <div class="privacy-section mb-4">
                    <h3><i class="bi bi-shield-lock-fill text-primary me-2"></i> Information We Collect</h3>
                    <p>At Shree Laxmi Amul Shopiee, we may collect the following types of information:</p>
                    <ul class="list-group mb-3">
                        <li class="list-group-item">
                            <strong>Personal Information:</strong> Name, contact information (phone number, email address), and address when you make inquiries or place orders.
                        </li>
                        <li class="list-group-item">
                            <strong>Transaction Information:</strong> Details about purchases you make at our store.
                        </li>
                        <li class="list-group-item">
                            <strong>Customer Preferences:</strong> Information about your product preferences and shopping habits to serve you better.
                        </li>
                        <li class="list-group-item">
                            <strong>Website Usage Data:</strong> Information about how you interact with our website, including IP address, browser type, pages visited, and time spent on our site.
                        </li>
                    </ul>
                    <p>We collect this information when you:</p>
                    <ul>
                        <li>Visit our store or website</li>
                        <li>Place an order or make a purchase</li>
                        <li>Contact us with inquiries</li>
                        <li>Fill out any forms on our website</li>
                        <li>Subscribe to our marketing communications</li>
                    </ul>
                </div>
                
                <div class="privacy-section mb-4">
                    <h3><i class="bi bi-graph-up text-primary me-2"></i> How We Use Your Information</h3>
                    <p>We use the information we collect for the following purposes:</p>
                    <div class="row row-cols-1 row-cols-md-2 g-4 mb-3">
                        <div class="col">
                            <div class="card h-100 border-0 shadow-sm">
                                <div class="card-body">
                                    <h5 class="card-title"><i class="bi bi-bag-check text-success me-2"></i> Process Transactions</h5>
                                    <p class="card-text">To process and fulfill your orders, including delivery arrangements for bulk orders.</p>
                                </div>
                            </div>
                        </div>
                        <div class="col">
                            <div class="card h-100 border-0 shadow-sm">
                                <div class="card-body">
                                    <h5 class="card-title"><i class="bi bi-headset text-warning me-2"></i> Customer Service</h5>
                                    <p class="card-text">To provide customer support, respond to inquiries, and address any concerns.</p>
                                </div>
                            </div>
                        </div>
                        <div class="col">
                            <div class="card h-100 border-0 shadow-sm">
                                <div class="card-body">
                                    <h5 class="card-title"><i class="bi bi-gear text-danger me-2"></i> Improve Our Services</h5>
                                    <p class="card-text">To analyze customer preferences and improve our product offerings and service quality.</p>
                                </div>
                            </div>
                        </div>
                        <div class="col">
                            <div class="card h-100 border-0 shadow-sm">
                                <div class="card-body">
                                    <h5 class="card-title"><i class="bi bi-megaphone text-primary me-2"></i> Marketing</h5>
                                    <p class="card-text">To inform you about promotions, new products, and special offers that may interest you.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
                <div class="privacy-section mb-4">
                    <h3><i class="bi bi-share-fill text-primary me-2"></i> Information Sharing</h3>
                    <p>We respect your privacy and do not sell, trade, or otherwise transfer your personal information to outside parties. We may share your information in the following limited circumstances:</p>
                    <ul>
                        <li><strong>Service Providers:</strong> With trusted third parties who assist us in operating our business, such as delivery services, as long as they agree to keep this information confidential.</li>
                        <li><strong>Legal Requirements:</strong> When we believe in good faith that disclosure is necessary to comply with the law, enforce our policies, or protect our or others' rights, property, or safety.</li>
                    </ul>
                </div>
                
                <div class="privacy-section mb-4">
                    <h3><i class="bi bi-lock-fill text-primary me-2"></i> Data Security</h3>
                    <p>We implement appropriate security measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction. However, no method of transmission over the Internet or electronic storage is 100% secure, and we cannot guarantee absolute security.</p>
                </div>
                
                <div class="privacy-section mb-4">
                    <h3><i class="bi bi-card-list text-primary me-2"></i> Your Rights</h3>
                    <p>You have the following rights regarding your personal information:</p>
                    <ul>
                        <li>The right to access the personal information we hold about you</li>
                        <li>The right to request correction of inaccurate information</li>
                        <li>The right to request deletion of your information</li>
                        <li>The right to opt out of marketing communications</li>
                    </ul>
                    <p>To exercise any of these rights, please contact us using the information provided below.</p>
                </div>
                
                <div class="privacy-section mb-4">
                    <h3><i class="bi bi-pencil-square text-primary me-2"></i> Changes to This Policy</h3>
                    <p>We may update this Privacy Policy from time to time. Any changes will be posted on this page with an updated revision date. We encourage you to review this policy periodically to stay informed about how we protect your information.</p>
                </div>
                
                <div class="privacy-section mb-4">
                    <h3><i class="bi bi-telephone-fill text-primary me-2"></i> Contact Us</h3>
                    <p>If you have any questions or concerns about this Privacy Policy or our data practices, please contact us:</p>
                    <div class="card bg-light">
                        <div class="card-body">
                            <address class="mb-0">
                                <strong>Shree Laxmi Amul Shopiee</strong><br>
                                210, pachmarg, road, opp. police station,<br>
                                Delwadi, Kudan, Maharashtra 401502<br>
                                <abbr title="Phone">Phone:</abbr> +91 9890377098<br>
                            </address>
                        </div>
                    </div>
                </div>
                
                <div class="text-center mt-5">
                    <p class="text-muted"><small>Last updated: January 2023</small></p>
                </div>
            </div>
        </div>
    </div>
</main>

<?php include 'footer.php'; ?>

<!-- Bootstrap JS Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
<!-- Ice Cream Background Animation -->
<script src="js/icecream-bg.js"></script>
<!-- InfinityFree compatibility fixes -->
<script src="infinity-fixes.js"></script>
</body>
</html>

